service: notes-app-mono-auth

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  profile:
    prod: p2c-prod 
    dev: p2c-dev 

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  profile: ${self:custom.profile.${self:custom.stage}}

resources:
  - ${file(resources/cognito-user-pool.yml)}
  - ${file(resources/cognito-identity-pool.yml)}
  - ${file(resources/cognito-default-auth-role.yml)}
  - ${file(resources/cognito-admins-auth-role.yml)}
  - ${file(resources/cognito-sellers-auth-role.yml)}
