Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      # Generate a name based on the stage
      UserPoolName: ${self:custom.stage}-mono-user-pool
      # Set email as an alias
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      # Generate an app client name based on the stage
      ClientName: ${self:custom.stage}-mono-user-pool-client
      UserPoolId:
        Ref: CognitoUserPool
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
      GenerateSecret: false

  CognitoAdminsGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      # Generate an app client name based on the stage
      GroupName: "Admins" 
      Precedence: 0
      UserPoolId:
        Ref: CognitoUserPool

  CognitoSellersGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      # Generate an app client name based on the stage
      GroupName: "Sellers" 
      Precedence: 0
      UserPoolId:
        Ref: CognitoUserPool

# Print out the Id of the User Pool
Outputs:
  UserPoolId:
    Value:
      Ref: CognitoUserPool

  UserPoolClientId:
    Value:
      Ref: CognitoUserPoolClient
