service: notes-app-mono-database

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  # Set our DynamoDB throughput for prod and all other non-prod stages.
  tableThroughputs:
    prod: 5
    default: 1
  tableThroughput: ${self:custom.tableThroughputs.${self:custom.stage}, self:custom.tableThroughputs.default}
  profile:
    prod: p2c-prod 
    dev: p2c-dev 
  tableDeletionPolicy:
    prod: Retain
    dev: Delete 

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  profile: ${self:custom.profile.${self:custom.stage}}

resources:
  Resources:
    NotesTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: ${self:custom.tableDeletionPolicy.${self:custom.stage}} 
      Properties:
        # Generate a name based on the stage
        TableName: ${self:custom.stage}-mono-notes-1
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: noteId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: noteId
            KeyType: RANGE
        # Set the capacity based on the stage
        ProvisionedThroughput:
          ReadCapacityUnits: ${self:custom.tableThroughput}
          WriteCapacityUnits: ${self:custom.tableThroughput}

  Outputs:
    NotesTableArn:
      Value:
         Fn::GetAtt:
          - NotesTable
          - Arn
      Export:
        Name: ${self:custom.stage}-NotesTableArn
    NotesTableName:
      Value:
        Ref: NotesTable
      Export:
        Name: NotesTableName
